import argparse
from collections import defaultdict
import re
"""
findRedundantMaplets.py

This script scans a MAPINFO-style text file for "redundant" maplets:
rows that share the same value in the second column (e.g., a resolution
like 0.0600) and have very similar coordinates within a user-specified
tolerance.

USAGE (command line):
    python findRedundantMaplets.py -f MAPINFO.TXT -t 2.0

Command-line options:
    -f, --file       Name of the input file (e.g., MAPINFO.TXT). Required.
    -t, --tolerance  Tolerance for comparing numeric coordinate columns.
                     A smaller number means a stricter match (less difference
                     allowed). Default is 0.0 (exact match).

FILE FORMATS AND SPECIAL HANDLING:

1. Header detection:
   - If the file begins with a header line whose first non-space characters
     spell "NAME" (case-insensitive), the script:
       * Treats the file as having a header.
       * Skips the first two lines entirely (header lines).
       * For each data row, it uses columns 3 and 4 (0-based indices 3 and 4)
         as the numeric coordinates to compare.
       * This type of file is generated by blessed RESIDUALS.

2. No header present:
   - If the file does NOT start with a "NAME" header line:
       * No lines are skipped at the top.
       * For each data row, it uses columns 2 and 3 (0-based indices 2 and 3)
         as the numeric coordinates to compare.
       * This type of file is generated by RESIDUALSX.

3. END marker:
   - If a line is encountered (after any skipped header) whose first
     non-space characters spell "END" (case-insensitive), the script:
       * Stops reading at that line.
       * Excludes that line and all lines after it from processing.

4. Whitespace-separated fields:
   - Each data line is split on arbitrary whitespace (spaces, tabs, etc.)
     so the file does not need to be comma-separated.
   - Example data row (no header):
       HF0001    0.0600 km    -63.0383    241.0141      4.1652 ...

MATCHING LOGIC:

- Rows are grouped by the value in the second column (index 1), which is
  treated as something like a resolution or scale (e.g., 0.0600).
  Only rows with the same value in this column are compared with one another.

- Within each group, the script compares every possible pair of rows
  (not just adjacent rows).

- For each pair, it reads two numeric "coordinate" columns:
    * With header   → indices 3 and 4
    * Without header→ indices 2 and 3

- If both coordinates differ by no more than the given tolerance:
      abs(x1 - x2) <= tolerance  AND  abs(y1 - y2) <= tolerance
  then the pair is reported as a match.

- Rows that do not have enough columns or whose coordinate fields cannot
  be converted to floats are silently skipped for matching.

This script is intended to help identify potentially redundant or
overlapping maplets in a MAPINFO-style file based on proximity in
coordinate space, resolution grouping, and an adjustable numeric tolerance.
"""

def read_data(file_name):
    """
    Reads and parses the input file.

    Behaviors:
      * Detects 'NAME' header (ignoring leading spaces).
      * If header exists, skip the first two lines.
      * Stops reading when a line beginning with 'END' appears.
      * Splits all remaining lines on arbitrary whitespace.
    """
    with open(file_name, "r") as f:
        lines = f.readlines()

    # --- Detect header ---
    first_nonempty_idx = None
    for i, line in enumerate(lines):
        if line.strip():
            first_nonempty_idx = i
            break

    has_header = False
    if first_nonempty_idx is not None:
        if lines[first_nonempty_idx].lstrip().upper().startswith("NAME"):
            has_header = True

    # If header present, skip first two lines
    start_idx = 2 if has_header else 0

    data = []
    for line in lines[start_idx:]:
        stripped = line.strip()
        if not stripped:
            continue

        # Stop at END line
        if stripped.upper().startswith("END"):
            break

        # Split on any whitespace
        row = re.split(r"\s+", stripped)
        data.append(row)

    return data, has_header


def find_matches(data, tolerance, x_idx, y_idx):
    """
    Finds pairs of rows with identical 2nd-column values (index 1)
    and similar numeric values in chosen columns x_idx and y_idx.
    """
    grouped = defaultdict(list)

    # Group rows by column 2 (index 1)
    for row in data:
        min_len = max(2, x_idx + 1, y_idx + 1)
        if len(row) < min_len:
            continue
        grouped[row[1]].append(row)

    matches = []

    for key, rows in grouped.items():
        if len(rows) < 2:
            continue

        for i in range(len(rows)):
            for j in range(i + 1, len(rows)):
                row1, row2 = rows[i], rows[j]

                try:
                    a1 = float(row1[x_idx])
                    a2 = float(row2[x_idx])
                    b1 = float(row1[y_idx])
                    b2 = float(row2[y_idx])
                except (ValueError, IndexError):
                    continue

                if abs(a1 - a2) <= tolerance and abs(b1 - b2) <= tolerance:
                    matches.append((row1, row2))

    return matches


def main():
    parser = argparse.ArgumentParser(
        description="Find redundant maplets with tolerance matching."
    )

    parser.add_argument(
        "-f", "--file",
        required=True,
        help="Input file name (e.g., MAPINFO.TXT)"
    )

    parser.add_argument(
        "-t", "--tolerance",
        type=float,
        default=0.0,
        help="Tolerance for matching numeric columns (default: 0.0)"
    )

    args = parser.parse_args()

    data, has_header = read_data(args.file)

    # Column rules:
    # Header present → compare columns 3 & 4 (indices 3,4)
    # No header      → compare columns 2 & 3 (indices 2,3)
    if has_header:
        x_idx, y_idx = 3, 4
    else:
        x_idx, y_idx = 2, 3

    matches = find_matches(data, args.tolerance, x_idx, y_idx)

    if matches:
        print("\nFound the following matches:")
        for row1, row2 in matches:
            print("-" * 60)
            print(f"Group (second column): {row1[1]}")
            print(f"  Row 1: {'  '.join(row1)}")
            print(f"  Row 2: {'  '.join(row2)}")
        print("\nAnalysis complete.")
    else:
        print("\nNo matching rows found with the specified tolerance.")


if __name__ == "__main__":
    main()

